services:

  postgres:

    image: postgres:17

    container_name: etl_postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: andre
      POSTGRES_PASSWORD: a92970f05
      POSTGRES_DB: etl_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    container_name: etl_metabase

    ports:
      - "3000:3000"

volumes:
  postgres_data: